config/routes.rb
Rails.application.routes.draw do
  resources :users, only: :show

  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :timesheets
  has_many :users, through: :timesheets

  scope :active,   -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  scope :by_tag,   -> (tag) { where('? = ANY (tags)', tag) }

  def estimate
    nil
  end

  def spent
    timesheets.sum(:time)
  end

  def underestimated?
    estimated ? spent > estimated : false
  end

  def members
    User.where(id: member_ids)
  end

  def tags
    super || []
  end
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :card
  belongs_to :user

  scope :within, -> (interval) {
    where(created_at: interval.first.to_time.beginning_of_day..interval.last.to_time.end_of_day)
  }

  %w(this last).each do |which|
    %w(day week month year).each do |interval|
      scope :"#{which}_#{interval}", -> {
        offset     = which == 'last' ? 1.send(interval) : 0
        start_date = Time.current.send("beginning_of_#{interval}") - offset
        end_date   = Time.current.send("end_of_#{interval}") - offset
        within(start_date..end_date)
      }

      scope :"#{which}_#{interval}_time", -> {
        send(:"#{which}_#{interval}").sum(:time)
      }
    end
  end

  def hours
    (time / 3600.0).round(1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :timesheets
  has_many :cards, through: :timesheets

  validates :email, presence: true
  validates :name, presence: true

  scope :by_tag, -> (tag) { where('? = ANY (tags)', tag) }

  scope :by_favro_ids, -> (favro_ids) {
    q = favro_ids.is_a?(Array) ? 'IN (?)' : '= ?'
    where("service_ids ->> 'favro' #{q}", favro_ids)
  }

  %w(this last).each do |which|
    %w(day week month year).each do |interval|
      define_method :"#{which}_#{interval}_time", -> {
        timesheets.send(:"#{which}_#{interval}_time")
      }
    end
  end

  def tags
    super || []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  ZOOMS = %w(day week month year)

  included do
    helper_method :start_date, :end_date, :interval, :zoom, :filter_params
  end

  protected

  def start_date
    @start_date ||= params[:start_date] ? Date.parse(params[:start_date]) : Time.current.beginning_of_week.to_date
  end

  def end_date
    @end_date ||= params[:end_date] ? Date.parse(params[:end_date]) : Time.current.to_date
  end

  def interval
    output = []
    date = start_date
    while date <= end_date.send(:"end_of_#{zoom}").to_date
      output << date.send(:"beginning_of_#{zoom}").to_date
      date += 1.send(zoom)
    end
    output
  end

  def zoom
    ZOOMS.include?(params[:zoom]) ? params[:zoom] : ZOOMS.first
  end

  def filter_params
    params.permit(:start_date, :end_date, :zoom, :interval).to_h
  end
end

app/controllers/concerns/grouped_timesheets.rb
module GroupedTimesheets
  extend ActiveSupport::Concern

  def timesheets_by_user
    timesheets.group_by do |ts|
      ts.user.name
    end
  end

  def timesheets_by_customer
    timesheets.group_by do |ts|
      (ts.card.tags.first || 'none').gsub(/\ ?\(.+/, "")
    end
  end

  def timesheets_by_card
    timesheets.group_by do |ts|
      ts.card.title
    end
  end

  included do
    helper_method  :timesheets_by_user, :timesheets_by_customer, :timesheets_by_card
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Filterable
  include GroupedTimesheets

  helper_method :users, :cards

  helper ChartHelper

  def index
  end

  protected

  def users
    @users ||= User.by_tag('developer').order(name: :asc)
  end

  def timesheets
    @timesheets ||= Timesheet.within(start_date..end_date)
  end

  def cards
    @users ||= Card.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Filterable
  include GroupedTimesheets

  helper_method :user, :timesheets

  helper ChartHelper

  def show
  end

  protected

  def user
    @user ||= User.find(params[:id])
  end

  def timesheets
    @timesheets ||= user.timesheets.within(start_date..end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper

  def chartize(interval:, grouped_timesheets:, zoom: nil)
    { labels: labelize_interval(interval: interval, zoom: zoom),
      datasets:
        grouped_timesheets.map do |title, timesheets|
          { type: 'bar',
            label: title,
            backgroundColor: interval.map { colorize(title) },
            data: pointize_interval(interval: interval, timesheets: timesheets, zoom: zoom)
          }
        end
    }.to_json
  end

  private

  def pointize_interval(interval:, timesheets:, zoom: nil)
    interval.map.with_index do |date, i|
      current_interval =
        if date == interval.last
          zoom ? date..date.send(:"end_of_#{zoom}") : date..date
        else
          date..(interval[i+1]-1)
        end
      timesheets.sum do |timesheet|
        timesheet_date = timesheet.created_at.to_date
        current_interval.include?(timesheet_date) ? timesheet.hours : 0
      end
    end
  end

  def labelize_interval(interval:, zoom: nil)
    case zoom
    when 'month'
      interval.map{|date| l(date, format: '%b %Y')}
    when 'week'
      interval.map do |date|
        last_day = date.end_of_week
        "#{l(date, format: '%d %b')} - #{l(last_day, format: '%d %b')}"
      end
    when 'year'
      interval.map{|date| date.year}
    else
      interval.map{|date| l(date, format: '%a, %d %b')}
    end
  end

  def colorize(string)
    "##{Digest::MD5.hexdigest(string)[0..5]}"
  end
end

app/views/charts/timesheets/_by_card.html.slim
.container
  h1 Cards

  canvas.js--chart data-chart=chartize(interval: interval, grouped_timesheets: timesheets_by_card, zoom: zoom)

  = render partial: 'charts/timesheets/summary', locals: { grouped_timesheets: timesheets_by_card }

app/views/charts/timesheets/_by_customer.html.slim
.container
  h1 Customers

  canvas.js--chart data-chart=chartize(interval: interval, grouped_timesheets: timesheets_by_customer, zoom: zoom)

  = render partial: 'charts/timesheets/summary', locals: { grouped_timesheets: timesheets_by_customer }

app/views/charts/timesheets/_by_user.html.slim
.container
  h1 Users

  canvas.js--chart data-chart=chartize(interval: interval, grouped_timesheets: timesheets_by_user, zoom: zoom)

  = render partial: 'charts/timesheets/summary', locals: { grouped_timesheets: timesheets_by_user }

app/views/charts/timesheets/_summary.html.slim
ruby:
  sorted_timesheets = grouped_timesheets.sort_by do |_, timesheets|
    -timesheets.sum(&:time)
  end.to_h

  labels = sorted_timesheets.keys

center
  .stats
    ul
      - labels.each do |label|
        li
          = sorted_timesheets[label].sum(&:hours).round
          span= label

app/views/dashboard/index.html.slim
coffee:
  init = ->
    $('.js--chart').each (_, el) ->
      $el = $(el)
      new Chart $el,
        type: 'bar'
        data: $el.data('chart')
        options:
          scales:
            yAxes: [
              ticks:
                beginAtZero: true
            ]
  document.addEventListener "turbolinks:load", ->
    $ ->
      init()

= render partial: 'shared/filters'

.dropdown
  .dropdown-container
    p.dropdown-description By developer
    p.dropdown-button Click to Select
    ul.dropdown-menu.dropdown-select
      - users.each do |user|
        li
          = link_to user.name, user_path(user, filter_params)

= render partial: 'charts/timesheets/by_user'
= render partial: 'charts/timesheets/by_customer'

app/views/layouts/application.html.slim
html
  head
    title SlackerTracker
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/navigation'
    .wrapper
      .container
        = yield

app/views/refills/_comment.html.erb
<div class="comment">
  <div class="comment-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png">
  </div>
  <div class="comment-content">
    <h1>First Comment Title or Author</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, aspernatur, quia modi minima debitis tempora ducimus quam vero impedit alias earum nemo error tenetur sed.</p>
    <p class="comment-detail">Date or details about this post</p>
  </div>
</div>

<div class="comment">
  <div class="comment-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png">
  </div>
  <div class="comment-content">
    <h1>Another One</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, aspernatur, quia modi minima debitis tempora ducimus quam vero impedit alias earum nemo error tenetur sed.</p>
    <p class="comment-detail">Date or details about this post</p>
  </div>
</div>

app/views/refills/_dropdown.html.erb
<div class="dropdown">
  <div class="dropdown-container">
    <p class="dropdown-description">Description</p>
    <p class="dropdown-button">Click to Select</p>
    <ul class="dropdown-menu dropdown-select">
      <li>Dropdown Menu Item</li>
      <li>Another Item</li>
      <li>Item Three</li>
      <li>The Last One</li>
    </ul>
  </div>
</div>

app/views/refills/_grid_items.html.erb
<div class="grid-items">
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Grid Item With an Image</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Another Wide Item</h1>
    <p>Lorem ipsum consectetur dolor sit amet, consectetur adipisicing elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Last Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Last Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>A Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
    <h1>Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
</div>

app/views/refills/_type_system_geometric.html.erb
<head>
  <link href='//fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'>
</head>

<article class="type-system-geometric">
  <p class="type">Article Type</p>
  <h1>Article Heading</h1>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, perferendis! Odit quisquam <code>code block</code> dicta illum ipsa quod natus iure aliquid necessitatibus veritatis, itaque magnam aliquam, dolorum nostrum nemo, explicabo perspiciatis nobis!</h2>

  <p class="date">30 Mar 2014</p>
  <p><span>Lorem ipsum dolor sit amet</span>, consectetur adipisicing elit. Consequatur a, ullam, voluptatum incidunt neque doloremque vel inventore distinctio laudantium harum</a> illo quam nulla dolor alias iure impedit! Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit.
    <a href="javascript:void(0)" class="read-more">Read More <span>&rsaquo;</span></a>
  </p>
  <h3>Subheading lorem</h3>
  <p><span>Consequatur ullam, voluptatum</span> incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit. Accusamus. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit! Accusamus.</p>
  <hr>
  <p class="author">Author Name</p>
</article>

app/views/shared/_filters.html.slim
form action='' method='GET'
  .search-tools
    .filters
      .filter
        label Interval
        div
          ol.filter-list
            - %w(start_date end_date).each do |date|
              li
                label= date.capitalize
                input type="date" name=date value=send(date)
      .filter
        label Zoom level
        div
          ol.filter-list
            - %w(day week month year).each do |zm|
              li
                label
                  input type="radio" name="zoom" value=zm checked=('checked' if zm == zoom)
                  = zm.capitalize

      .filter.trigger
        input type='submit' value='Update'

app/views/shared/_navigation.html.slim
header.centered-navigation
  .centered-navigation-wrapper
    a href="javascript:void(0)" class="mobile-logo"
      img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo image"
    a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu" MENU
    nav role="navigation"
      ul id="js-centered-navigation-menu" class="centered-navigation-menu show"
        li class="nav-link" : a href="/" Dashboard
        /
          li class="nav-link" : a href="javascript:void(0)" About Us
          li class="nav-link" : a href="javascript:void(0)" Contact
          li class="nav-link logo"
            a href="javascript:void(0)" class="logo"
              img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo image"
          li class="nav-link"
            a href="javascript:void(0)" Testimonials
        /li id="js-centered-more" class="nav-link more"
          a href="javascript:void(0)" More
          ul class="submenu"
            li : a href="javascript:void(0)" Submenu Item
            li : a href="javascript:void(0)" Another Item
            li class="more"
              a href="javascript:void(0)"Item with submenu
              ul class="submenu fly-out-right"
                li : a href="javascript:void(0)" Sub-submenu Item
                li : a href="javascript:void(0)" Another Item
            li class="more"
              a href="javascript:void(0)" Another submenu
              ul class="submenu fly-out-right"
                li : a href="javascript:void(0)" Sub-submenu
                li : a href="javascript:void(0)" An Item
        li class="nav-link" : a href="javascript:void(0)" Sign up

app/views/users/show.html.slim
coffee:
  init = ->
    $('.js--chart').each (_, el) ->
      $el = $(el)
      new Chart $el,
        type: 'bar'
        data: $el.data('chart')
        options:
          scales:
            yAxes: [
              ticks:
                beginAtZero: true
            ]
  document.addEventListener "turbolinks:load", ->
    $ ->
      init()

= render partial: 'shared/filters'

h1= user.name

= render partial: 'charts/timesheets/by_user'
= render partial: 'charts/timesheets/by_customer'
= render partial: 'charts/timesheets/by_card'